name: conventional-commits

on:
  pull_request:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Conventional Commits
        uses: cocogitto/cocogitto-action@v3
        with:
          check: true
          check-latest-tag-only: true
          release: false
